# Generated by Django 4.2.2 on 2023-06-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagons', '0003_alter_category_options_alter_wagons_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Категория'),
        ),
    ]
